### ISSUE TITLE
Is it possible to print HTML elements with this plugin?

### ISSUE THREAD

**Issue by AldeirJampier** [c00/cordova-plugin-taffprint#1]

**Comment by c00** [comment]
Nope, it just prints texts and pictures. I haven't checked if the framework supports html.

**Comment by AldeirJampier** [comment]
I checked one in your code, and I read some tutorials, and I saw that it is possible to convert html to image with html2canvas, but I ran into a problem with this plugin, because it only prints the defined image, it would be simple, implement the Loading image encoded in base64, for printing, inside the printImage function?

Thank you for your attention!

**Comment by c00** [comment]
That is definitely something I'd want in there in the future, however, currently it is not possible and I don't have the time to add this now.

However, feel free to go at it yourself. The plugin is small, so it should be easy enough.
